# Site settings
title: Welcome to My World
description: A professional and Personal Web description
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Santhosh Reddy Malgireddy
user_description: I am an Engineer by profession, Learner by aspirations and Compassionate Human Being by nature. My research topics are Data science, Neural Networksm Machine Learning, Big data analytics and Software Developer Real time analytics and  always tries to evolve ing to keep myself balanced  interestBicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Science Engineer | Big Data Engineer | Computer Science Engineer
email: mailto:malgireddysanthoshreddy@gmail.com
github_username:  https://github.com/smalgireddy
linkedln:  https://www.linkedin.com/in/santhosh333/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
